CREATE DATABASE customer_db;
USE customer_db;

select * from customer_sales_analysis_cleaned;

rename table customer_sales_analysis_cleaned to customer_sales;
select * from customer_sales;
#Total no of revenue generated by male and female
select gender, sum(purchase_amount) as revenue 
from customer_sales
group by gender;

#Customers which used the discount but spend more than avg purchase amount 
select customer_id, purchase_amount 
from customer_sales 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_sales);

# which are the top 5 products with highest average review rating 

select item_purchased, round(avg(review_rating),2) as Avg_Product_revenue
from customer_sales 
group by item_purchased order by avg(review_rating) desc
limit 5;

#Compare the avg purchase amounts btwn standard and express shipping 
select shipping_type, round(avg(purchase_amount),2) as Avg_Purchase_amount
from customer_sales
where shipping_type in ('Express','Standard')
group by shipping_type;

#Do subscribed customers spend more. Compare avg spend and total revenue 
#betwn subscribers and non subscribers 

select subscription_status, count(customer_id) as Customer_count, 
round(avg(purchase_amount),2) as Avg_purchase_amount,
sum(purchase_amount) as Total_revenue
from customer_sales 
group by subscription_status ;
select * from customer_sales;
#Which 5 products have the highest percentage of purchases with discount applied. 

select item_purchased, 
round(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),2) as purchase_amount, discount_applied
from customer_sales 
where discount_applied = 'Yes'
group by item_purchased order by sum(purchase_amount) desc
limit 5;

#Divide customers into new, returning and loyal depending on there total number of purchases

with customer_type as(
select previous_purchases,
case 
	when previous_purchases < 2 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    when previous_purchases > 10 then 'Loyal'
end as customer_segment
from customer_sales
)
select customer_segment, count(*) as 'num of customers' 
from customer_type
group by customer_segment;
select * from customer_sales;
#What are the top 3 most purchased products within each category 

with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc ) as item_rank
from customer_sales
group by category,item_purchased
)
select item_rank, category, item_purchased, total_orders 
from item_counts
where item_rank <=3;

SHOW VARIABLES LIKE 'port';

